// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: payments.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	OrderID       string                 `protobuf:"bytes,2,opt,name=orderID,proto3" json:"orderID,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"`
	AmountPaid    float32                `protobuf:"fixed32,4,opt,name=amountPaid,proto3" json:"amountPaid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *CreateTransactionRequest) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *CreateTransactionRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmountPaid() float32 {
	if x != nil {
		return x.AmountPaid
	}
	return 0
}

type TransactionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionID     string                 `protobuf:"bytes,1,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	UserID            string                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	OrderID           string                 `protobuf:"bytes,3,opt,name=orderID,proto3" json:"orderID,omitempty"`
	AmountPaid        float32                `protobuf:"fixed32,4,opt,name=amountPaid,proto3" json:"amountPaid,omitempty"`
	PaymentMethod     string                 `protobuf:"bytes,5,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"`
	TransactionStatus string                 `protobuf:"bytes,6,opt,name=transactionStatus,proto3" json:"transactionStatus,omitempty"`
	Timestamp         string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionResponse) GetTransactionID() string {
	if x != nil {
		return x.TransactionID
	}
	return ""
}

func (x *TransactionResponse) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *TransactionResponse) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *TransactionResponse) GetAmountPaid() float32 {
	if x != nil {
		return x.AmountPaid
	}
	return 0
}

func (x *TransactionResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *TransactionResponse) GetTransactionStatus() string {
	if x != nil {
		return x.TransactionStatus
	}
	return ""
}

func (x *TransactionResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_payments_proto protoreflect.FileDescriptor

const file_payments_proto_rawDesc = "" +
	"\n" +
	"\x0epayments.proto\x12\apayment\"\x92\x01\n" +
	"\x18CreateTransactionRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x18\n" +
	"\aorderID\x18\x02 \x01(\tR\aorderID\x12$\n" +
	"\rpaymentMethod\x18\x03 \x01(\tR\rpaymentMethod\x12\x1e\n" +
	"\n" +
	"amountPaid\x18\x04 \x01(\x02R\n" +
	"amountPaid\"\xff\x01\n" +
	"\x13TransactionResponse\x12$\n" +
	"\rtransactionID\x18\x01 \x01(\tR\rtransactionID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\x12\x18\n" +
	"\aorderID\x18\x03 \x01(\tR\aorderID\x12\x1e\n" +
	"\n" +
	"amountPaid\x18\x04 \x01(\x02R\n" +
	"amountPaid\x12$\n" +
	"\rpaymentMethod\x18\x05 \x01(\tR\rpaymentMethod\x12,\n" +
	"\x11transactionStatus\x18\x06 \x01(\tR\x11transactionStatus\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp2f\n" +
	"\x0ePaymentService\x12T\n" +
	"\x11CreateTransaction\x12!.payment.CreateTransactionRequest\x1a\x1c.payment.TransactionResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_payments_proto_rawDescOnce sync.Once
	file_payments_proto_rawDescData []byte
)

func file_payments_proto_rawDescGZIP() []byte {
	file_payments_proto_rawDescOnce.Do(func() {
		file_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payments_proto_rawDesc), len(file_payments_proto_rawDesc)))
	})
	return file_payments_proto_rawDescData
}

var file_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_payments_proto_goTypes = []any{
	(*CreateTransactionRequest)(nil), // 0: payment.CreateTransactionRequest
	(*TransactionResponse)(nil),      // 1: payment.TransactionResponse
}
var file_payments_proto_depIdxs = []int32{
	0, // 0: payment.PaymentService.CreateTransaction:input_type -> payment.CreateTransactionRequest
	1, // 1: payment.PaymentService.CreateTransaction:output_type -> payment.TransactionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payments_proto_init() }
func file_payments_proto_init() {
	if File_payments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payments_proto_rawDesc), len(file_payments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payments_proto_goTypes,
		DependencyIndexes: file_payments_proto_depIdxs,
		MessageInfos:      file_payments_proto_msgTypes,
	}.Build()
	File_payments_proto = out.File
	file_payments_proto_goTypes = nil
	file_payments_proto_depIdxs = nil
}
