// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: order_queue.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Allowed status values
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_COOKING            Status = 1
	Status_PREPARING          Status = 2
	Status_READY              Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "COOKING",
		2: "PREPARING",
		3: "READY",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"COOKING":            1,
		"PREPARING":          2,
		"READY":              3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_order_queue_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_order_queue_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_order_queue_proto_rawDescGZIP(), []int{0}
}

// The Order message corresponds to one row in order_queue.
type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                      // UUID
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`             // UUID of the actual order
	Status        Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=order_queue.Status" json:"status,omitempty"`     // cooking, preparing, ready
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`                         // integer priority
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"` // timestamptz
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_queue_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Order) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Order) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// For Create: client sends an OrderCreateRequest without id & last_updated.
type OrderCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=order_queue.Status" json:"status,omitempty"` // optional: defaults to PREPARING if omitted
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`                     // optional: defaults to 1 if omitted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreateRequest) Reset() {
	*x = OrderCreateRequest{}
	mi := &file_order_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateRequest) ProtoMessage() {}

func (x *OrderCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateRequest.ProtoReflect.Descriptor instead.
func (*OrderCreateRequest) Descriptor() ([]byte, []int) {
	return file_order_queue_proto_rawDescGZIP(), []int{1}
}

func (x *OrderCreateRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCreateRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *OrderCreateRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// Response returns the full Order with generated fields populated.
type OrderCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreateResponse) Reset() {
	*x = OrderCreateResponse{}
	mi := &file_order_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateResponse) ProtoMessage() {}

func (x *OrderCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateResponse.ProtoReflect.Descriptor instead.
func (*OrderCreateResponse) Descriptor() ([]byte, []int) {
	return file_order_queue_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCreateResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// For Read: client requests by id.
type OrderGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderGetRequest) Reset() {
	*x = OrderGetRequest{}
	mi := &file_order_queue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderGetRequest) ProtoMessage() {}

func (x *OrderGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_queue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderGetRequest.ProtoReflect.Descriptor instead.
func (*OrderGetRequest) Descriptor() ([]byte, []int) {
	return file_order_queue_proto_rawDescGZIP(), []int{3}
}

func (x *OrderGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response returns the Order.
type OrderGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderGetResponse) Reset() {
	*x = OrderGetResponse{}
	mi := &file_order_queue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderGetResponse) ProtoMessage() {}

func (x *OrderGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_queue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderGetResponse.ProtoReflect.Descriptor instead.
func (*OrderGetResponse) Descriptor() ([]byte, []int) {
	return file_order_queue_proto_rawDescGZIP(), []int{4}
}

func (x *OrderGetResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// For Update: client sends the full Order; id must be set.
type OrderUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderUpdateRequest) Reset() {
	*x = OrderUpdateRequest{}
	mi := &file_order_queue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdateRequest) ProtoMessage() {}

func (x *OrderUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_queue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdateRequest.ProtoReflect.Descriptor instead.
func (*OrderUpdateRequest) Descriptor() ([]byte, []int) {
	return file_order_queue_proto_rawDescGZIP(), []int{5}
}

func (x *OrderUpdateRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// Response returns the updated Order.
type OrderUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderUpdateResponse) Reset() {
	*x = OrderUpdateResponse{}
	mi := &file_order_queue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdateResponse) ProtoMessage() {}

func (x *OrderUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_queue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdateResponse.ProtoReflect.Descriptor instead.
func (*OrderUpdateResponse) Descriptor() ([]byte, []int) {
	return file_order_queue_proto_rawDescGZIP(), []int{6}
}

func (x *OrderUpdateResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// For Delete: client requests by id.
type OrderDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDeleteRequest) Reset() {
	*x = OrderDeleteRequest{}
	mi := &file_order_queue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDeleteRequest) ProtoMessage() {}

func (x *OrderDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_queue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDeleteRequest.ProtoReflect.Descriptor instead.
func (*OrderDeleteRequest) Descriptor() ([]byte, []int) {
	return file_order_queue_proto_rawDescGZIP(), []int{7}
}

func (x *OrderDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response is empty.
type OrderDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDeleteResponse) Reset() {
	*x = OrderDeleteResponse{}
	mi := &file_order_queue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDeleteResponse) ProtoMessage() {}

func (x *OrderDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_queue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDeleteResponse.ProtoReflect.Descriptor instead.
func (*OrderDeleteResponse) Descriptor() ([]byte, []int) {
	return file_order_queue_proto_rawDescGZIP(), []int{8}
}

func (x *OrderDeleteResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

// List all or filter by status (optional)
type OrderListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If set, only return orders with this status
	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=order_queue.Status" json:"status,omitempty"`
	// Pagination (optional)
	PageSize      int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListRequest) Reset() {
	*x = OrderListRequest{}
	mi := &file_order_queue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListRequest) ProtoMessage() {}

func (x *OrderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_queue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListRequest.ProtoReflect.Descriptor instead.
func (*OrderListRequest) Descriptor() ([]byte, []int) {
	return file_order_queue_proto_rawDescGZIP(), []int{9}
}

func (x *OrderListRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *OrderListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *OrderListRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type OrderListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListResponse) Reset() {
	*x = OrderListResponse{}
	mi := &file_order_queue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListResponse) ProtoMessage() {}

func (x *OrderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_queue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListResponse.ProtoReflect.Descriptor instead.
func (*OrderListResponse) Descriptor() ([]byte, []int) {
	return file_order_queue_proto_rawDescGZIP(), []int{10}
}

func (x *OrderListResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *OrderListResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_order_queue_proto protoreflect.FileDescriptor

const file_order_queue_proto_rawDesc = "" +
	"\n" +
	"\x11order_queue.proto\x12\vorder_queue\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xba\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.order_queue.StatusR\x06status\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12=\n" +
	"\flast_updated\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"x\n" +
	"\x12OrderCreateRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.order_queue.StatusR\x06status\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\"?\n" +
	"\x13OrderCreateResponse\x12(\n" +
	"\x05order\x18\x01 \x01(\v2\x12.order_queue.OrderR\x05order\"!\n" +
	"\x0fOrderGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x10OrderGetResponse\x12(\n" +
	"\x05order\x18\x01 \x01(\v2\x12.order_queue.OrderR\x05order\">\n" +
	"\x12OrderUpdateRequest\x12(\n" +
	"\x05order\x18\x01 \x01(\v2\x12.order_queue.OrderR\x05order\"?\n" +
	"\x13OrderUpdateResponse\x12(\n" +
	"\x05order\x18\x01 \x01(\v2\x12.order_queue.OrderR\x05order\"$\n" +
	"\x12OrderDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x13OrderDeleteResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"{\n" +
	"\x10OrderListRequest\x12+\n" +
	"\x06status\x18\x01 \x01(\x0e2\x13.order_queue.StatusR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"g\n" +
	"\x11OrderListResponse\x12*\n" +
	"\x06orders\x18\x01 \x03(\v2\x12.order_queue.OrderR\x06orders\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*G\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCOOKING\x10\x01\x12\r\n" +
	"\tPREPARING\x10\x02\x12\t\n" +
	"\x05READY\x10\x032\x9f\x03\n" +
	"\x11OrderQueueService\x12P\n" +
	"\vCreateOrder\x12\x1f.order_queue.OrderCreateRequest\x1a .order_queue.OrderCreateResponse\x12G\n" +
	"\bGetOrder\x12\x1c.order_queue.OrderGetRequest\x1a\x1d.order_queue.OrderGetResponse\x12P\n" +
	"\vUpdateOrder\x12\x1f.order_queue.OrderUpdateRequest\x1a .order_queue.OrderUpdateResponse\x12P\n" +
	"\vDeleteOrder\x12\x1f.order_queue.OrderDeleteRequest\x1a .order_queue.OrderDeleteResponse\x12K\n" +
	"\n" +
	"ListOrders\x12\x1d.order_queue.OrderListRequest\x1a\x1e.order_queue.OrderListResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_order_queue_proto_rawDescOnce sync.Once
	file_order_queue_proto_rawDescData []byte
)

func file_order_queue_proto_rawDescGZIP() []byte {
	file_order_queue_proto_rawDescOnce.Do(func() {
		file_order_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_queue_proto_rawDesc), len(file_order_queue_proto_rawDesc)))
	})
	return file_order_queue_proto_rawDescData
}

var file_order_queue_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_order_queue_proto_goTypes = []any{
	(Status)(0),                   // 0: order_queue.Status
	(*Order)(nil),                 // 1: order_queue.Order
	(*OrderCreateRequest)(nil),    // 2: order_queue.OrderCreateRequest
	(*OrderCreateResponse)(nil),   // 3: order_queue.OrderCreateResponse
	(*OrderGetRequest)(nil),       // 4: order_queue.OrderGetRequest
	(*OrderGetResponse)(nil),      // 5: order_queue.OrderGetResponse
	(*OrderUpdateRequest)(nil),    // 6: order_queue.OrderUpdateRequest
	(*OrderUpdateResponse)(nil),   // 7: order_queue.OrderUpdateResponse
	(*OrderDeleteRequest)(nil),    // 8: order_queue.OrderDeleteRequest
	(*OrderDeleteResponse)(nil),   // 9: order_queue.OrderDeleteResponse
	(*OrderListRequest)(nil),      // 10: order_queue.OrderListRequest
	(*OrderListResponse)(nil),     // 11: order_queue.OrderListResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_order_queue_proto_depIdxs = []int32{
	0,  // 0: order_queue.Order.status:type_name -> order_queue.Status
	12, // 1: order_queue.Order.last_updated:type_name -> google.protobuf.Timestamp
	0,  // 2: order_queue.OrderCreateRequest.status:type_name -> order_queue.Status
	1,  // 3: order_queue.OrderCreateResponse.order:type_name -> order_queue.Order
	1,  // 4: order_queue.OrderGetResponse.order:type_name -> order_queue.Order
	1,  // 5: order_queue.OrderUpdateRequest.order:type_name -> order_queue.Order
	1,  // 6: order_queue.OrderUpdateResponse.order:type_name -> order_queue.Order
	13, // 7: order_queue.OrderDeleteResponse.empty:type_name -> google.protobuf.Empty
	0,  // 8: order_queue.OrderListRequest.status:type_name -> order_queue.Status
	1,  // 9: order_queue.OrderListResponse.orders:type_name -> order_queue.Order
	2,  // 10: order_queue.OrderQueueService.CreateOrder:input_type -> order_queue.OrderCreateRequest
	4,  // 11: order_queue.OrderQueueService.GetOrder:input_type -> order_queue.OrderGetRequest
	6,  // 12: order_queue.OrderQueueService.UpdateOrder:input_type -> order_queue.OrderUpdateRequest
	8,  // 13: order_queue.OrderQueueService.DeleteOrder:input_type -> order_queue.OrderDeleteRequest
	10, // 14: order_queue.OrderQueueService.ListOrders:input_type -> order_queue.OrderListRequest
	3,  // 15: order_queue.OrderQueueService.CreateOrder:output_type -> order_queue.OrderCreateResponse
	5,  // 16: order_queue.OrderQueueService.GetOrder:output_type -> order_queue.OrderGetResponse
	7,  // 17: order_queue.OrderQueueService.UpdateOrder:output_type -> order_queue.OrderUpdateResponse
	9,  // 18: order_queue.OrderQueueService.DeleteOrder:output_type -> order_queue.OrderDeleteResponse
	11, // 19: order_queue.OrderQueueService.ListOrders:output_type -> order_queue.OrderListResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_order_queue_proto_init() }
func file_order_queue_proto_init() {
	if File_order_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_queue_proto_rawDesc), len(file_order_queue_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_queue_proto_goTypes,
		DependencyIndexes: file_order_queue_proto_depIdxs,
		EnumInfos:         file_order_queue_proto_enumTypes,
		MessageInfos:      file_order_queue_proto_msgTypes,
	}.Build()
	File_order_queue_proto = out.File
	file_order_queue_proto_goTypes = nil
	file_order_queue_proto_depIdxs = nil
}
