// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: calculate_discounted_products.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float32                `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
	Discount      float32                `protobuf:"fixed32,2,opt,name=discount,proto3" json:"discount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscountRequest) Reset() {
	*x = DiscountRequest{}
	mi := &file_calculate_discounted_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscountRequest) ProtoMessage() {}

func (x *DiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculate_discounted_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscountRequest.ProtoReflect.Descriptor instead.
func (*DiscountRequest) Descriptor() ([]byte, []int) {
	return file_calculate_discounted_products_proto_rawDescGZIP(), []int{0}
}

func (x *DiscountRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *DiscountRequest) GetDiscount() float32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

type DiscountResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DiscountedPrice float32                `protobuf:"fixed32,1,opt,name=discounted_price,json=discountedPrice,proto3" json:"discounted_price,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiscountResponse) Reset() {
	*x = DiscountResponse{}
	mi := &file_calculate_discounted_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscountResponse) ProtoMessage() {}

func (x *DiscountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculate_discounted_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscountResponse.ProtoReflect.Descriptor instead.
func (*DiscountResponse) Descriptor() ([]byte, []int) {
	return file_calculate_discounted_products_proto_rawDescGZIP(), []int{1}
}

func (x *DiscountResponse) GetDiscountedPrice() float32 {
	if x != nil {
		return x.DiscountedPrice
	}
	return 0
}

var File_calculate_discounted_products_proto protoreflect.FileDescriptor

const file_calculate_discounted_products_proto_rawDesc = "" +
	"\n" +
	"#calculate_discounted_products.proto\x12\x04menu\"C\n" +
	"\x0fDiscountRequest\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x02R\x05price\x12\x1a\n" +
	"\bdiscount\x18\x02 \x01(\x02R\bdiscount\"=\n" +
	"\x10DiscountResponse\x12)\n" +
	"\x10discounted_price\x18\x01 \x01(\x02R\x0fdiscountedPrice2Q\n" +
	"\vMenuService\x12B\n" +
	"\x11CalculateDiscount\x12\x15.menu.DiscountRequest\x1a\x16.menu.DiscountResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_calculate_discounted_products_proto_rawDescOnce sync.Once
	file_calculate_discounted_products_proto_rawDescData []byte
)

func file_calculate_discounted_products_proto_rawDescGZIP() []byte {
	file_calculate_discounted_products_proto_rawDescOnce.Do(func() {
		file_calculate_discounted_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calculate_discounted_products_proto_rawDesc), len(file_calculate_discounted_products_proto_rawDesc)))
	})
	return file_calculate_discounted_products_proto_rawDescData
}

var file_calculate_discounted_products_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_calculate_discounted_products_proto_goTypes = []any{
	(*DiscountRequest)(nil),  // 0: menu.DiscountRequest
	(*DiscountResponse)(nil), // 1: menu.DiscountResponse
}
var file_calculate_discounted_products_proto_depIdxs = []int32{
	0, // 0: menu.MenuService.CalculateDiscount:input_type -> menu.DiscountRequest
	1, // 1: menu.MenuService.CalculateDiscount:output_type -> menu.DiscountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculate_discounted_products_proto_init() }
func file_calculate_discounted_products_proto_init() {
	if File_calculate_discounted_products_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculate_discounted_products_proto_rawDesc), len(file_calculate_discounted_products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculate_discounted_products_proto_goTypes,
		DependencyIndexes: file_calculate_discounted_products_proto_depIdxs,
		MessageInfos:      file_calculate_discounted_products_proto_msgTypes,
	}.Build()
	File_calculate_discounted_products_proto = out.File
	file_calculate_discounted_products_proto_goTypes = nil
	file_calculate_discounted_products_proto_depIdxs = nil
}
