// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cart struct {
	UserID      string      `json:"userID"`
	Items       []*CartItem `json:"items"`
	TotalAmount float64     `json:"totalAmount"`
}

type CartItem struct {
	ID       string  `json:"id"`
	FoodItem string  `json:"foodItem"`
	Quantity int32   `json:"quantity"`
	Price    float64 `json:"price"`
}

type CartItemInput struct {
	FoodItem string  `json:"foodItem"`
	Quantity int32   `json:"quantity"`
	Price    float64 `json:"price"`
}

type Mutation struct {
}

type Payment struct {
	OrderID           string  `json:"orderID"`
	PaymentMethod     string  `json:"paymentMethod"`
	PaymentInfo       *string `json:"paymentInfo,omitempty"`
	AmountPaid        float64 `json:"amountPaid"`
	TransactionID     string  `json:"transactionID"`
	TransactionStatus string  `json:"transactionStatus"`
	Timestamp         string  `json:"timestamp"`
}

type Query struct {
}

type Receipt struct {
	TransactionID     string  `json:"transactionID"`
	UserID            string  `json:"userID"`
	OrderID           string  `json:"orderID"`
	AmountPaid        float64 `json:"amountPaid"`
	PaymentMethod     string  `json:"paymentMethod"`
	Timestamp         string  `json:"timestamp"`
	TransactionStatus string  `json:"transactionStatus"`
}
